// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chart: typeof import('./components/Chart/index.vue')['default']
    ComponentNotFound: typeof import('./components/ComponentNotFound/index.vue')['default']
    Hamburger: typeof import('./components/Hamburger/index.vue')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpPromotion: typeof import('~icons/ep/promotion')['default']
    IEpRefreshRight: typeof import('~icons/ep/refresh-right')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    ISvgTranslation: typeof import('~icons/svg/translation')['default']
    LangSelect: typeof import('./components/LangSelect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/global/SvgIcon/index.vue')['default']
  }
}
