// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IEpUser: typeof import('~icons/ep/user')['default']
    ISvgSun: typeof import('~icons/svg/sun')['default']
    ISvgTranslation: typeof import('~icons/svg/translation')['default']
    LangSelect: typeof import('./components/LangSelect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/global/SvgIcon/index.vue')['default']
  }
}
